[package]
name = "async-serve"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
async-std = "1"
async-listen = "0.2"
futures = "0.3"
slog = "2"

[dev-dependencies]
async-ctrlc = "1"
sloggers = "0.3"
