[package]
name = "async-listen"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
ctrlc = "3"
async-std = "1"
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
